/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vews;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import database.dao.DaoClientes;

/**
 *
 * @author Alex
 */
public class PrCliente extends javax.swing.JPanel {

    public static PrCliente cl;

    /**
     * Creates new form Inicio
     */
    public PrCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        NOMBRE = new javax.swing.JLabel();
        AP_PATERNO = new javax.swing.JLabel();
        AP_MATERNO = new javax.swing.JLabel();
        FECHA_REG = new javax.swing.JLabel();
        CORREO = new javax.swing.JLabel();
        DIRECCIÓN = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApPaterno = new javax.swing.JTextField();
        jTextFieldApMaterno = new javax.swing.JTextField();
        jTextFieldFechaReg = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        searchbar = new javax.swing.JTextField();
        FILTRO = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();
        BUSCAR = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CALLE = new javax.swing.JLabel();
        EXTERIOR = new javax.swing.JLabel();
        jTextFieldExterior = new javax.swing.JTextField();
        jTextFieldCalle = new javax.swing.JTextField();
        INTERIOR = new javax.swing.JLabel();
        jTextFieldInterior = new javax.swing.JTextField();
        COLONIA = new javax.swing.JLabel();
        jTextFieldColonia = new javax.swing.JTextField();
        DELEGACIÓN = new javax.swing.JLabel();
        jTextFieldAlcalMun = new javax.swing.JTextField();
        CP = new javax.swing.JLabel();
        jTextFieldCP = new javax.swing.JTextField();
        AGREGAR_BOTON = new javax.swing.JButton();
        GUARDAR_BOTON = new javax.swing.JButton();
        EDITAR_BOTON = new javax.swing.JButton();
        ELIMINAR_BOTON = new javax.swing.JButton();
        ESTADO = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldEstado = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(940, 570));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1040, 560));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NOMBRE.setText("NOMBRE");
        jPanel1.add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        AP_PATERNO.setText("APELLIDO PATERNO");
        jPanel1.add(AP_PATERNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        AP_MATERNO.setText("APELLIDO MATERNO");
        jPanel1.add(AP_MATERNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        FECHA_REG.setText("FECHA DE REGISTRO");
        jPanel1.add(FECHA_REG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        CORREO.setText("CORREO");
        jPanel1.add(CORREO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        DIRECCIÓN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DIRECCIÓN.setText("DIRECCIÓN");
        jPanel1.add(DIRECCIÓN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, -1));

        jTextFieldNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 320, -1));

        jTextFieldApPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApPaternoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 260, -1));

        jTextFieldApMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApMaternoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 260, -1));

        jTextFieldFechaReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaRegActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 250, -1));

        jTextFieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 320, -1));

        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        jPanel1.add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 280, -1));

        FILTRO.setText("FILTRAR:");
        jPanel1.add(FILTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        resultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NOMBRE", "AP PAT", "AP MAT", "FECHA REG", "CORREO", "DIRECCIÓN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resultsTable.setCellSelectionEnabled(true);
        resultsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(resultsTable);
        resultsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 450, 250));

        BUSCAR.setText("BUSCAR");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });
        jPanel1.add(BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Jost", 0, 48)); // NOI18N
        jLabel8.setText("CLIENTE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 210, 60));

        CALLE.setText("CALLE");
        jPanel1.add(CALLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        EXTERIOR.setText("EXTERIOR");
        jPanel1.add(EXTERIOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jTextFieldExterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldExteriorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldExterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 70, -1));

        jTextFieldCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCalleActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 330, -1));

        INTERIOR.setText("INTERIOR");
        jPanel1.add(INTERIOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));
        jPanel1.add(jTextFieldInterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 70, -1));

        COLONIA.setText("COLONIA");
        jPanel1.add(COLONIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jTextFieldColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColoniaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 140, -1));

        DELEGACIÓN.setText("ALCAL/MUN");
        jPanel1.add(DELEGACIÓN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));
        jPanel1.add(jTextFieldAlcalMun, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 110, -1));

        CP.setText("C.P.");
        jPanel1.add(CP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));
        jPanel1.add(jTextFieldCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 60, 30));

        AGREGAR_BOTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/añadir cpem.png"))); // NOI18N
        AGREGAR_BOTON.setContentAreaFilled(false);
        AGREGAR_BOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREGAR_BOTONActionPerformed(evt);
            }
        });
        jPanel1.add(AGREGAR_BOTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        GUARDAR_BOTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        GUARDAR_BOTON.setContentAreaFilled(false);
        jPanel1.add(GUARDAR_BOTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, -1, -1));

        EDITAR_BOTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar usuari.png"))); // NOI18N
        EDITAR_BOTON.setContentAreaFilled(false);
        EDITAR_BOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITAR_BOTONActionPerformed(evt);
            }
        });
        jPanel1.add(EDITAR_BOTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        ELIMINAR_BOTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        ELIMINAR_BOTON.setContentAreaFilled(false);
        jPanel1.add(ELIMINAR_BOTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, -1, -1));

        ESTADO.setText("ESTADO");
        jPanel1.add(ESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));
        jPanel1.add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 290, -1));

        jTextFieldEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 140, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 900, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed

        jTextFieldNombre.setText(""); // Elimina el texto inicial
        jTextFieldNombre.setEditable(true); // Hace que no se pueda editar
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldApPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApPaternoActionPerformed

        jTextFieldNombre.setText(""); // Elimina el texto inicial
        jTextFieldNombre.setEditable(true); // Hace que no se pueda editar
    }//GEN-LAST:event_jTextFieldApPaternoActionPerformed

    private void jTextFieldApMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApMaternoActionPerformed

        jTextFieldNombre.setText(""); // Elimina el texto inicial
        jTextFieldNombre.setEditable(true); // Hace que no se pueda editar
    }//GEN-LAST:event_jTextFieldApMaternoActionPerformed

    private void jTextFieldFechaRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaRegActionPerformed

        jTextFieldNombre.setText(""); // Elimina el texto inicial
        jTextFieldNombre.setEditable(true); // Hace que no se pueda editar
    }//GEN-LAST:event_jTextFieldFechaRegActionPerformed

    private void jTextFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoActionPerformed

        jTextFieldNombre.setText(""); // Elimina el texto inicial
        jTextFieldNombre.setEditable(true); // Hace que no se pueda editar
    }//GEN-LAST:event_jTextFieldCorreoActionPerformed

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed

    }//GEN-LAST:event_searchbarActionPerformed

    private void resultsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultsTableMouseClicked
    int filaSeleccionada = resultsTable.getSelectedRow();

    if (filaSeleccionada != -1) {
        // Obtener los valores de las columnas de la fila seleccionada
        String nombre = resultsTable.getValueAt(filaSeleccionada, 0).toString();
        String apPaterno = resultsTable.getValueAt(filaSeleccionada, 1).toString();
        String apMaterno = resultsTable.getValueAt(filaSeleccionada, 2).toString();
        String fechaReg = resultsTable.getValueAt(filaSeleccionada, 3).toString();
        String correo = resultsTable.getValueAt(filaSeleccionada, 4).toString();

        // Elementos de la dirección desde la tabla
        String calle = resultsTable.getValueAt(filaSeleccionada, 5).toString();
        String exterior = resultsTable.getValueAt(filaSeleccionada, 6).toString();
        String interior = resultsTable.getValueAt(filaSeleccionada, 7).toString();
        String colonia = resultsTable.getValueAt(filaSeleccionada, 8).toString();
        String alcalMun = resultsTable.getValueAt(filaSeleccionada, 9).toString();
        String estado = resultsTable.getValueAt(filaSeleccionada, 10).toString();
        String cp = resultsTable.getValueAt(filaSeleccionada, 11).toString();

        // Asignar los valores a los cuadros de texto
        jTextFieldNombre.setText(nombre);
        jTextFieldApPaterno.setText(apPaterno);
        jTextFieldApMaterno.setText(apMaterno);
        jTextFieldFechaReg.setText(fechaReg);
        jTextFieldCorreo.setText(correo);

        // Asignar los valores de la dirección
        jTextFieldCalle.setText(calle);
        jTextFieldExterior.setText(exterior);
        jTextFieldInterior.setText(interior);
        jTextFieldColonia.setText(colonia);
        jTextFieldAlcalMun.setText(alcalMun);
        jTextFieldEstado.setText(estado);
        jTextFieldCP.setText(cp);
    }
    }//GEN-LAST:event_resultsTableMouseClicked

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
   String filtro = searchbar.getText().trim();

    if (filtro.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, escribe un nombre para buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    DaoClientes daoCliente = new DaoClientes();
    List<Object[]> resultados = daoCliente.searchClientsByName(filtro);

    if (resultados == null || resultados.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No se encontraron resultados.", "Información", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Nombre");
    model.addColumn("Apellido Paterno");
    model.addColumn("Apellido Materno");
    model.addColumn("Fecha Registro");
    model.addColumn("Correo");
    model.addColumn("Calle");
    model.addColumn("Número Exterior");
    model.addColumn("Número Interior");
    model.addColumn("Colonia");
    model.addColumn("Alcaldía/Municipio");
    model.addColumn("Estado");
    model.addColumn("Código Postal");

    for (Object[] cliente : resultados) {
        model.addRow(new Object[]{
            cliente[1], // Nombre
            cliente[2], // Apellido Paterno
            cliente[3], // Apellido Materno
            cliente[4], // Fecha Registro
            cliente[5], // Correo
            cliente[6], // Calle
            cliente[7], // Número Exterior
            cliente[8], // Número Interior
            cliente[9], // Colonia
            cliente[10], // Alcaldía/Municipio
            cliente[11], // Estado
            cliente[12]  // Código Postal
        });
    }

    resultsTable.setModel(model);
} 

// Método para mostrar un solo cliente (puedes adaptar esto a tu interfaz)
private void mostrarCliente(Object[] cliente) {
    // Mostrar un mensaje con los datos del cliente, por ejemplo:
    String clienteInfo = "Nombre: " + cliente[1] + " " + cliente[2] + " " + cliente[3] +
                         "\nCorreo: " + cliente[5] + "\nDirección: " + cliente[6];
    JOptionPane.showMessageDialog(this, clienteInfo, "Cliente Encontrado", JOptionPane.INFORMATION_MESSAGE);

} 

// Método para mostrar los resultados en una tabla o en otro componente
private void mostrarResultados(List<Object[]> resultados) {
    // Establecer el modelo de la tabla sin la columna "DIRECCIÓN"
    DefaultTableModel model = new DefaultTableModel(
        new Object [][] {}, // Inicializar la tabla vacía
        new String [] {
            "NOMBRE", "AP PAT", "AP MAT", "FECHA REG", "CORREO"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };

    // Limpiar la tabla antes de agregar los nuevos resultados
    model.setRowCount(0);

    // Recorrer los resultados y agregar cada cliente a la tabla
    for (Object[] cliente : resultados) {
        model.addRow(cliente); // Agregar los datos del cliente a la tabla
    }

    // Establecer el modelo actualizado a la JTable
    resultsTable.setModel(model);

    }//GEN-LAST:event_BUSCARActionPerformed

    private void jTextFieldExteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldExteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldExteriorActionPerformed

    private void jTextFieldColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColoniaActionPerformed

    private void AGREGAR_BOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREGAR_BOTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AGREGAR_BOTONActionPerformed

    private void EDITAR_BOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITAR_BOTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDITAR_BOTONActionPerformed

    private void jTextFieldCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCalleActionPerformed

    private void jTextFieldEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AGREGAR_BOTON;
    private javax.swing.JLabel AP_MATERNO;
    private javax.swing.JLabel AP_PATERNO;
    private javax.swing.JButton BUSCAR;
    private javax.swing.JLabel CALLE;
    private javax.swing.JLabel COLONIA;
    private javax.swing.JLabel CORREO;
    private javax.swing.JLabel CP;
    private javax.swing.JLabel DELEGACIÓN;
    private javax.swing.JLabel DIRECCIÓN;
    private javax.swing.JButton EDITAR_BOTON;
    private javax.swing.JButton ELIMINAR_BOTON;
    private javax.swing.JLabel ESTADO;
    private javax.swing.JLabel EXTERIOR;
    private javax.swing.JLabel FECHA_REG;
    private javax.swing.JLabel FILTRO;
    private javax.swing.JButton GUARDAR_BOTON;
    private javax.swing.JLabel INTERIOR;
    private javax.swing.JLabel NOMBRE;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAlcalMun;
    private javax.swing.JTextField jTextFieldApMaterno;
    private javax.swing.JTextField jTextFieldApPaterno;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldCalle;
    private javax.swing.JTextField jTextFieldColonia;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldExterior;
    private javax.swing.JTextField jTextFieldFechaReg;
    private javax.swing.JTextField jTextFieldInterior;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTable resultsTable;
    private javax.swing.JTextField searchbar;
    // End of variables declaration//GEN-END:variables

    public void setLocation(double d) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
