/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vews;
import database.dao.DaoClientes;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class PrProveedor extends javax.swing.JPanel {

    public static PrProveedor cl;

    /**
     * Creates new form Inicio
     */
    public PrProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        fondo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        productos = new javax.swing.JPanel();
        jLabelFechaVenta = new javax.swing.JLabel();
        jTextFieldFechaVenta = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldFechaVenta2 = new javax.swing.JTextField();
        jLabelFechaVenta2 = new javax.swing.JLabel();
        jTextFieldFechaVenta4 = new javax.swing.JTextField();
        jLabelFechaVenta3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ELIMINAR_BOTON = new javax.swing.JButton();
        jTextFieldFechaVenta8 = new javax.swing.JTextField();
        jTextFieldFechaVenta9 = new javax.swing.JTextField();
        DIRECCIÓN = new javax.swing.JLabel();
        CALLE = new javax.swing.JLabel();
        EXTERIOR = new javax.swing.JLabel();
        INTERIOR = new javax.swing.JLabel();
        CP = new javax.swing.JLabel();
        COLONIA = new javax.swing.JLabel();
        COLONIA1 = new javax.swing.JLabel();
        ESTADO = new javax.swing.JLabel();
        jTextFieldFechaVenta10 = new javax.swing.JTextField();
        jTextFieldFechaVenta11 = new javax.swing.JTextField();
        jTextFieldFechaVenta12 = new javax.swing.JTextField();
        jTextFieldFechaVenta14 = new javax.swing.JTextField();
        jTextFieldFechaVenta15 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        AGREGAR_BOTON = new javax.swing.JButton();
        DELEGACIÓN = new javax.swing.JLabel();
        jTextFieldAlcalMun = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFechaVenta5 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultsTable2 = new javax.swing.JTable();
        searchbar2 = new javax.swing.JTextField();
        FILTRO1 = new javax.swing.JLabel();
        BUSCAR1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(940, 570));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1040, 560));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Jost", 0, 48)); // NOI18N
        jLabel9.setText("PROVEEDOR");
        fondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 306, 60));

        productos.setBackground(new java.awt.Color(255, 255, 255));
        productos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        productos.setForeground(new java.awt.Color(204, 204, 204));
        productos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFechaVenta.setText("NOMBRE CONTACTO");
        productos.add(jLabelFechaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));
        productos.add(jTextFieldFechaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 320, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        productos.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 160, -1));

        jLabel3.setText("TELEFONO");
        productos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 90, 20));

        jLabel4.setText("LADA");
        productos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        jTextFieldFechaVenta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaVenta2ActionPerformed(evt);
            }
        });
        productos.add(jTextFieldFechaVenta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 320, -1));

        jLabelFechaVenta2.setText("NOMBRE EMPRESA");
        productos.add(jLabelFechaVenta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jTextFieldFechaVenta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaVenta4ActionPerformed(evt);
            }
        });
        productos.add(jTextFieldFechaVenta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 140, -1));

        jLabelFechaVenta3.setText("EXTENSIÓN");
        productos.add(jLabelFechaVenta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 336, 50, 50));

        ELIMINAR_BOTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        ELIMINAR_BOTON.setContentAreaFilled(false);
        ELIMINAR_BOTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productos.add(ELIMINAR_BOTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 346, -1, -1));
        productos.add(jTextFieldFechaVenta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 99, -1));
        productos.add(jTextFieldFechaVenta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 100, -1));

        DIRECCIÓN.setFont(new java.awt.Font("Jost", 0, 12)); // NOI18N
        DIRECCIÓN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DIRECCIÓN.setText("DIRECCIÓN");
        productos.add(DIRECCIÓN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        CALLE.setText("CALLE");
        productos.add(CALLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 20));

        EXTERIOR.setText("EXTERIOR");
        productos.add(EXTERIOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 20));

        INTERIOR.setText("INTERIOR");
        productos.add(INTERIOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 20));

        CP.setText("C.P.");
        productos.add(CP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 40, 20));

        COLONIA.setText("COLONIA");
        productos.add(COLONIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 416, -1, -1));

        COLONIA1.setText("COLONIA");
        productos.add(COLONIA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, 20));

        ESTADO.setText("ESTADO");
        productos.add(ESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, 20));
        productos.add(jTextFieldFechaVenta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 90, -1));
        productos.add(jTextFieldFechaVenta11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 64, -1));
        productos.add(jTextFieldFechaVenta12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 190, -1));
        productos.add(jTextFieldFechaVenta14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 100, -1));
        productos.add(jTextFieldFechaVenta15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar usuari.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 346, 40, 40));

        AGREGAR_BOTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/añadir cpem.png"))); // NOI18N
        AGREGAR_BOTON.setContentAreaFilled(false);
        AGREGAR_BOTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AGREGAR_BOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREGAR_BOTONActionPerformed(evt);
            }
        });
        productos.add(AGREGAR_BOTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 346, -1, -1));

        DELEGACIÓN.setText("ALCAL/MUN");
        productos.add(DELEGACIÓN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));
        productos.add(jTextFieldAlcalMun, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 110, -1));

        jLabel5.setText("CORREO");
        productos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 60, 20));

        jTextFieldFechaVenta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaVenta5ActionPerformed(evt);
            }
        });
        productos.add(jTextFieldFechaVenta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 220, -1));

        fondo.add(productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 410));

        resultsTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        resultsTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NOMBRE", "CONTACTO", "LADA", "TELEFONO", "DIRECCIÓN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resultsTable2.setCellSelectionEnabled(true);
        resultsTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultsTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(resultsTable2);
        resultsTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        fondo.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 130, 410, 380));

        searchbar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbar2ActionPerformed(evt);
            }
        });
        fondo.add(searchbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 100, 280, -1));

        FILTRO1.setText("FILTRAR:");
        fondo.add(FILTRO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 100, -1, 20));

        BUSCAR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        BUSCAR1.setBorder(null);
        BUSCAR1.setBorderPainted(false);
        BUSCAR1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BUSCAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCAR1ActionPerformed(evt);
            }
        });
        fondo.add(BUSCAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(859, 90, -1, -1));

        bg.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, 910, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void AGREGAR_BOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREGAR_BOTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AGREGAR_BOTONActionPerformed

    private void jTextFieldFechaVenta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaVenta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaVenta4ActionPerformed

    private void resultsTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultsTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_resultsTable2MouseClicked

    private void searchbar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbar2ActionPerformed

    private void BUSCAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCAR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUSCAR1ActionPerformed

    private void jTextFieldFechaVenta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaVenta2ActionPerformed
       jTextFieldFechaVenta2.setText("");
       jTextFieldFechaVenta2.setEditable(false);// Elimina el texto inicial
    }//GEN-LAST:event_jTextFieldFechaVenta2ActionPerformed

    private void jTextFieldFechaVenta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaVenta5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaVenta5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AGREGAR_BOTON;
    private javax.swing.JButton BUSCAR1;
    private javax.swing.JLabel CALLE;
    private javax.swing.JLabel COLONIA;
    private javax.swing.JLabel COLONIA1;
    private javax.swing.JLabel CP;
    private javax.swing.JLabel DELEGACIÓN;
    private javax.swing.JLabel DIRECCIÓN;
    private javax.swing.JButton ELIMINAR_BOTON;
    private javax.swing.JLabel ESTADO;
    private javax.swing.JLabel EXTERIOR;
    private javax.swing.JLabel FILTRO1;
    private javax.swing.JLabel INTERIOR;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel fondo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFechaVenta;
    private javax.swing.JLabel jLabelFechaVenta2;
    private javax.swing.JLabel jLabelFechaVenta3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldAlcalMun;
    private javax.swing.JTextField jTextFieldFechaVenta;
    private javax.swing.JTextField jTextFieldFechaVenta10;
    private javax.swing.JTextField jTextFieldFechaVenta11;
    private javax.swing.JTextField jTextFieldFechaVenta12;
    private javax.swing.JTextField jTextFieldFechaVenta14;
    private javax.swing.JTextField jTextFieldFechaVenta15;
    private javax.swing.JTextField jTextFieldFechaVenta2;
    private javax.swing.JTextField jTextFieldFechaVenta4;
    private javax.swing.JTextField jTextFieldFechaVenta5;
    private javax.swing.JTextField jTextFieldFechaVenta8;
    private javax.swing.JTextField jTextFieldFechaVenta9;
    private javax.swing.JPanel productos;
    private javax.swing.JTable resultsTable2;
    private javax.swing.JTextField searchbar2;
    // End of variables declaration//GEN-END:variables

    public void setLocation(double d) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
