/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vews;

import database.dao.DaoCompras;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author leona
 */
public class TablaDeCompraNueva extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TablaDeCompraNueva() {
        
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        // Listener para reforzar el cierre correcto
    addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent evt) {
            System.out.println("Cerrando sólo TablaDeCompraNueva");
            dispose(); // Cierra sólo esta ventana
            
        }
    });
    setFechaActual(); // Establecer la fecha actual en el cuadro de texto
    cargarProductosTabla();
    cargarProveedores();
    setUsuario();
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
 private void setUsuario() {
    // Dividir el nombre completo en partes (separadas por espacios)
    String[] partesNombre = usuarioAutenticado.split(" ");

    // Verificar si hay al menos dos palabras
    if (partesNombre.length >= 2) {
        // El primer nombre es siempre la primera palabra
        String primerNombre = partesNombre[0];

        // Construir el apellido paterno desde la segunda palabra hasta la penúltima (si hay más de dos palabras)
        StringBuilder apellidoPaterno = new StringBuilder();
        for (int i = 1; i < partesNombre.length - 1; i++) {
            apellidoPaterno.append(partesNombre[i]).append(" ");
        }

        // Si el nombre tiene solo dos palabras, la segunda palabra es el apellido paterno
        if (partesNombre.length == 2) {
            apellidoPaterno.append(partesNombre[1]);
        }

        // Remover el espacio extra al final
        String apellidoPaternoFinal = apellidoPaterno.toString().trim();

        // Formatear y establecer el texto en el JLabel Usuario
        Usuario.setText(primerNombre + " " + apellidoPaternoFinal);
    } else {
        // Si solo hay un nombre, mostrarlo
        Usuario.setText(usuarioAutenticado);
    }
}
 
 private String usuarioAutenticado;
 
 private void filtrarProductosPorProveedor() {
    String proveedorSeleccionado = (String) Proveedores.getSelectedItem();
    String idProveedor = (String) Proveedores.getClientProperty(proveedorSeleccionado); // Obtén el ID

    if (idProveedor != null) {
        try {
            DaoCompras daoCompras = new DaoCompras();
            List<Object[]> productos = daoCompras.obtenerProductosPorProveedor(idProveedor);

            // Configura la tabla de productos
            DefaultTableModel modelo = new DefaultTableModel(
                new String[]{"ID Producto", "Nombre"}, 0
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            for (Object[] producto : productos) {
                modelo.addRow(producto);
            }

            ProductosTabla.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al filtrar productos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
}
private void cargarProveedores() {
    try {
        DaoCompras daoCompras = new DaoCompras();
        List<Object[]> proveedores = daoCompras.obtenerProveedores(); // ID y Nombre

        Proveedores.removeAllItems();
        for (Object[] proveedor : proveedores) {
            Proveedores.addItem(proveedor[1].toString()); // Mostrar NOMBRE_EMPRESA
            Proveedores.putClientProperty(proveedor[1].toString(), proveedor[0].toString()); // Asocia ID_PROVEEDOR
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar proveedores: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
    private void quitarProductoDelCarrito() {
    int filaSeleccionada = CarritoTabla.getSelectedRow(); // Obtiene la fila seleccionada en CarritoTabla

    if (filaSeleccionada != -1) { // Verifica que haya una fila seleccionada
        DefaultTableModel modeloCarrito = (DefaultTableModel) CarritoTabla.getModel();
        
        // Obtiene la cantidad actual
        Object cantidadObj = modeloCarrito.getValueAt(filaSeleccionada, 2);
        int cantidadActual = cantidadObj != null ? Integer.parseInt(cantidadObj.toString()) : 0;

        if (cantidadActual > 1) {
            // Reduce la cantidad en 1
            modeloCarrito.setValueAt(cantidadActual - 1, filaSeleccionada, 2);
        } else {
            // Si la cantidad es 1, elimina la fila
            modeloCarrito.removeRow(filaSeleccionada);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un producto para quitar del carrito.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }
}
    private void agregarProductoAlCarrito() {
    int filaSeleccionada = ProductosTabla.getSelectedRow(); // Obtiene la fila seleccionada

    if (filaSeleccionada != -1) { // Verifica que haya una fila seleccionada
        // Obtiene los datos del producto seleccionado
        String idProducto = ProductosTabla.getValueAt(filaSeleccionada, 0).toString(); // ID Producto
        String nombreProducto = ProductosTabla.getValueAt(filaSeleccionada, 1).toString(); // Nombre Producto

        // Obtiene el modelo de CarritoTabla
        DefaultTableModel modeloCarrito = (DefaultTableModel) CarritoTabla.getModel();

        boolean productoEncontrado = false;

        // Busca si el producto ya está en el carrito
        for (int i = 0; i < modeloCarrito.getRowCount(); i++) {
            Object valorCelda = modeloCarrito.getValueAt(i, 0); // Obtén el valor de la celda
            if (valorCelda != null && valorCelda.toString().equals(idProducto)) {
                // Producto encontrado, incrementa la cantidad
                int cantidadActual = Integer.parseInt(modeloCarrito.getValueAt(i, 2).toString());
                modeloCarrito.setValueAt(cantidadActual + 1, i, 2);
                productoEncontrado = true;
                break;
            }
        }

        if (!productoEncontrado) {
            // Producto no encontrado, agrega una nueva fila al principio de la tabla
            modeloCarrito.insertRow(0, new Object[]{idProducto, nombreProducto, 1});
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un producto para agregar al carrito.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }
}
    private void cargarProductosTabla() {
    try {
        // Crear instancia del DAO
        DaoCompras daoCompras = new DaoCompras();
        
        // Obtener los productos desde la base de datos
        List<Object[]> productos = daoCompras.obtenerProductos();

        // Crear el modelo de la tabla
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"ID Producto", "Nombre"}, 0 // Encabezados de la tabla
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Hacer todas las celdas no editables
                return false;
            }
        };

        // Agregar los productos al modelo
        for (Object[] producto : productos) {
            model.addRow(producto);
        }

        // Asignar el modelo a la tabla
        ProductosTabla.setModel(model);

    } catch (Exception e) {
        // Mostrar mensaje de error si ocurre un problema
        JOptionPane.showMessageDialog(this, "Error al cargar los productos: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }
  private void setFechaActual() {
        LocalDate fechaActual = LocalDate.now(); // Obtiene la fecha actual
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("YYYY-MM-DD"); // Define el formato deseado
        FechaDelDia.setText(fechaActual.format(formatter)); // Establece la fecha en el JTextField
    }
   

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Productos = new javax.swing.JScrollPane();
        ProductosTabla = new javax.swing.JTable();
        Carrito = new javax.swing.JScrollPane();
        CarritoTabla = new javax.swing.JTable();
        Fecha = new javax.swing.JLabel();
        FechaDelDia = new javax.swing.JTextField();
        QuitarDeLaCompra = new javax.swing.JButton();
        AgregarALaCompra = new javax.swing.JButton();
        Comprar = new javax.swing.JButton();
        ProveedoresLabe = new javax.swing.JLabel();
        Proveedores = new javax.swing.JComboBox<>();
        EstadoDeCompra = new javax.swing.JLabel();
        EstadosDeCompra = new javax.swing.JComboBox<>();
        UsuarioLable = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Productos.setAutoscrolls(true);

        ProductosTabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ProductosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "NOMBRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductosTabla.setCellSelectionEnabled(true);
        ProductosTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductosTablaMouseClicked(evt);
            }
        });
        ProductosTabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ProductosTablaKeyPressed(evt);
            }
        });
        Productos.setViewportView(ProductosTabla);
        ProductosTabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 640, 130));

        Carrito.setAutoscrolls(true);

        CarritoTabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CarritoTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCTO", "CANTIDAD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CarritoTabla.setCellSelectionEnabled(true);
        CarritoTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarritoTablaMouseClicked(evt);
            }
        });
        CarritoTabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CarritoTablaKeyPressed(evt);
            }
        });
        Carrito.setViewportView(CarritoTabla);
        CarritoTabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(Carrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 370, 130));

        Fecha.setText("FECHA DE COMPRA");
        jPanel1.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 20));

        FechaDelDia.setEditable(false);
        FechaDelDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaDelDiaActionPerformed(evt);
            }
        });
        jPanel1.add(FechaDelDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 170, 30));

        QuitarDeLaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-menos.png"))); // NOI18N
        QuitarDeLaCompra.setBorder(null);
        QuitarDeLaCompra.setBorderPainted(false);
        QuitarDeLaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarDeLaCompraActionPerformed(evt);
            }
        });
        jPanel1.add(QuitarDeLaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 60, 50));

        AgregarALaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar (2).png"))); // NOI18N
        AgregarALaCompra.setBorder(null);
        AgregarALaCompra.setBorderPainted(false);
        AgregarALaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarALaCompraActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarALaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 60, 50));

        Comprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compra.png"))); // NOI18N
        jPanel1.add(Comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        ProveedoresLabe.setText("PROVEEDOR");
        jPanel1.add(ProveedoresLabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 70, 30));

        Proveedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedoresActionPerformed(evt);
            }
        });
        jPanel1.add(Proveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 130, 30));

        EstadoDeCompra.setText("ESTADO DE COMPRA");
        jPanel1.add(EstadoDeCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 100, 30));

        EstadosDeCompra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(EstadosDeCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 110, 30));

        UsuarioLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jPanel1.add(UsuarioLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        Usuario.setText("jLabel2");
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductosTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosTablaMouseClicked
        
    }//GEN-LAST:event_ProductosTablaMouseClicked

    private void ProductosTablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProductosTablaKeyPressed
      
    }//GEN-LAST:event_ProductosTablaKeyPressed

    private void CarritoTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarritoTablaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CarritoTablaMouseClicked

    private void CarritoTablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CarritoTablaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarritoTablaKeyPressed

    private void FechaDelDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaDelDiaActionPerformed
        setFechaActual();
       

        // TODO add your handling code here:
    }//GEN-LAST:event_FechaDelDiaActionPerformed

    private void AgregarALaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarALaCompraActionPerformed
        agregarProductoAlCarrito(); // Llama al método 
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarALaCompraActionPerformed

    private void QuitarDeLaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarDeLaCompraActionPerformed
        quitarProductoDelCarrito();
        // TODO add your handling code here:
    }//GEN-LAST:event_QuitarDeLaCompraActionPerformed

    private void ProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedoresActionPerformed
         
         filtrarProductosPorProveedor();
        // TODO add your handling code here:
    }//GEN-LAST:event_ProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaDeCompraNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaDeCompraNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaDeCompraNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaDeCompraNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaDeCompraNueva().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarALaCompra;
    private javax.swing.JScrollPane Carrito;
    private javax.swing.JTable CarritoTabla;
    private javax.swing.JButton Comprar;
    private javax.swing.JLabel EstadoDeCompra;
    private javax.swing.JComboBox<String> EstadosDeCompra;
    private javax.swing.JLabel Fecha;
    private javax.swing.JTextField FechaDelDia;
    private javax.swing.JScrollPane Productos;
    private javax.swing.JTable ProductosTabla;
    private javax.swing.JComboBox<String> Proveedores;
    private javax.swing.JLabel ProveedoresLabe;
    private javax.swing.JButton QuitarDeLaCompra;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel UsuarioLable;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
