/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vews;

/**
 *
 * @author leona
 */
public class TablaDeCompraNueva extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TablaDeCompraNueva() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        // Listener para reforzar el cierre correcto
    addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent evt) {
            System.out.println("Cerrando sólo TablaDeCompraNueva");
            dispose(); // Cierra sólo esta ventana
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Productos = new javax.swing.JScrollPane();
        ProductosTabla = new javax.swing.JTable();
        Carrito = new javax.swing.JScrollPane();
        CarritoTabla = new javax.swing.JTable();
        Fecha = new javax.swing.JLabel();
        FechaDelDia = new javax.swing.JTextField();
        QuitarDeLaCompra = new javax.swing.JButton();
        AgregarALaCompra = new javax.swing.JButton();
        Comprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Productos.setAutoscrolls(true);

        ProductosTabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ProductosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "PRODUCTOS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductosTabla.setCellSelectionEnabled(true);
        ProductosTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductosTablaMouseClicked(evt);
            }
        });
        ProductosTabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ProductosTablaKeyPressed(evt);
            }
        });
        Productos.setViewportView(ProductosTabla);

        jPanel1.add(Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 450, 120));

        Carrito.setAutoscrolls(true);

        CarritoTabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CarritoTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "PRODUCTO", "CANTIDAD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CarritoTabla.setCellSelectionEnabled(true);
        CarritoTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarritoTablaMouseClicked(evt);
            }
        });
        CarritoTabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CarritoTablaKeyPressed(evt);
            }
        });
        Carrito.setViewportView(CarritoTabla);

        jPanel1.add(Carrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 370, 130));

        Fecha.setText("FECHA DE COMPRA");
        jPanel1.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        FechaDelDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaDelDiaActionPerformed(evt);
            }
        });
        jPanel1.add(FechaDelDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 39, 140, 20));

        QuitarDeLaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-menos.png"))); // NOI18N
        QuitarDeLaCompra.setBorder(null);
        QuitarDeLaCompra.setBorderPainted(false);
        jPanel1.add(QuitarDeLaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 30, 30));

        AgregarALaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar (2).png"))); // NOI18N
        AgregarALaCompra.setBorder(null);
        AgregarALaCompra.setBorderPainted(false);
        jPanel1.add(AgregarALaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 30, 30));

        Comprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compra.png"))); // NOI18N
        jPanel1.add(Comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductosTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosTablaMouseClicked

    }//GEN-LAST:event_ProductosTablaMouseClicked

    private void ProductosTablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProductosTablaKeyPressed

    }//GEN-LAST:event_ProductosTablaKeyPressed

    private void CarritoTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarritoTablaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CarritoTablaMouseClicked

    private void CarritoTablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CarritoTablaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarritoTablaKeyPressed

    private void FechaDelDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaDelDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaDelDiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaDeCompraNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaDeCompraNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaDeCompraNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaDeCompraNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaDeCompraNueva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarALaCompra;
    private javax.swing.JScrollPane Carrito;
    private javax.swing.JTable CarritoTabla;
    private javax.swing.JButton Comprar;
    private javax.swing.JLabel Fecha;
    private javax.swing.JTextField FechaDelDia;
    private javax.swing.JScrollPane Productos;
    private javax.swing.JTable ProductosTabla;
    private javax.swing.JButton QuitarDeLaCompra;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
